[package]
name = "my-vocabulary-lib"
version = "0.1.0"
authors = ["searene <mycityofsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.4", features = ["sqlite"] }
dotenv = "0.15.0"
lazy_static = "1.4.0"
